<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Centering</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Richard W Morris</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="rcode.html">R examples</a>
</li>
<li>
  <a href="CV.pdf">CV</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Centering</h1>

</div>


<p><font size="3"></p>
<p><br></p>
<div id="between--and-within-group-centering" class="section level2">
<h2>Between- and within-group centering</h2>
<p>In a multilevel model (where data is clustered within groups), the
total effect of a (lower level) predictor can be separated into the
<strong>within-group</strong> component and the
<strong>between-group</strong> component. Entering raw predictor values
or grand-mean centered values into the model will produce a weighted*
composite of both components (and interpretation will be
confounded).</p>
<p>However, if the <em>group mean</em> values of the predictor are
<em>also</em> entered in the model then the raw predictor coefficient
represents the within-group effect (and the mean predictor coefficient
would represent the difference between the between- and within-group
effect - the <strong>contextual effect</strong>).</p>
<p>If the <em>group mean centered</em> values are entered as the
predictor (with or without a group mean predictor), the regression
coefficient represents the <strong>within-group</strong> effect.</p>
<p>Adding the group mean values as a predictor will then estimate the
<strong>between-group</strong> effect.</p>
<p>This post is based on this <a
href="https://stats.stackexchange.com/questions/403693/are-covariates-in-a-mixed-model-estimated-between-group-within-group-or-somewh/404493#404493">stackexchange
post</a></p>
<pre class="r"><code>set.seed(4) # 3 works

beta = -1
sigma = 5

ngp = 5
rpt = 10

generatedata = function(gp, n){
  x = rnorm(n) + gp
  y = beta*x + 3*gp + rnorm(n, sd=sigma)
  tibble(x=x, y=y, p=gp)
}

data &lt;- map(1:5, generatedata, rpt) |&gt; 
  bind_rows() |&gt; 
  mutate(p = factor(p))

# data = as.data.frame(do.call(rbind, lapply(1:ngp, generatedata, rpt)))
# data$p = factor(data$p)

ggplot(data, aes(x = x, y = y, color = p)) +
  geom_point() +
  geom_smooth(aes(group = p), method = &quot;lm&quot;, formula = &#39;y ~ x&#39;, se=F) </code></pre>
<p><img src="centering_files/figure-html/generatedata-1.png" width="672" /></p>
<p><br></p>
<p><br></p>
<p>The amount of between-group variance in the predictor is shown
below:</p>
<pre class="r"><code>x.model = lmer(x ~ 1 + (1|p), data=data)

icc &lt;- function(lmerfit) {
  
  n &lt;- as.data.frame(VarCorr(lmerfit))[, &quot;vcov&quot;][1]
  d &lt;- sum(as.data.frame(VarCorr(lmerfit))[, &quot;vcov&quot;])
  n / d
  
}

icc(x.model)</code></pre>
<pre><code>## [1] 0.577</code></pre>
<p>Fully 57.731 percent of the variance in x sits between the levels of
<span class="math inline">\(p\)</span> (i.e.,
<em>between-group</em>).</p>
<p><br></p>
<p>A linear mixed model (LMM) with the uncentered <span
class="math inline">\(x\)</span> as the predictor provides the following
result:</p>
<pre class="r"><code>mixed.model = lmer(y ~ 1 + x + (1|p), data=data)

summary(mixed.model)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: y ~ 1 + x + (1 | p)
##    Data: data
## 
## REML criterion at convergence: 283
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7244 -0.6487 -0.0648  0.5227  2.8702 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  p        (Intercept) 34.9     5.91    
##  Residual             13.9     3.73    
## Number of obs: 50, groups:  p, 5
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   12.808      3.209    3.99
## x             -2.134      0.555   -3.85
## 
## Correlation of Fixed Effects:
##   (Intr)
## x -0.543</code></pre>
<p>A one unit change in <span class="math inline">\(x\)</span> is
associated with a -2.134 unit change in <span
class="math inline">\(y\)</span>. But it is unclear whether this change
is happening within <span class="math inline">\(x\)</span> or between
<span class="math inline">\(p\)</span>.</p>
<p><br></p>
<p>One way to focus on the within-group effect is to estimate a fixed
effects model (also called a <em>varying intercept model</em>!). This
tells you the <strong>within-group effect</strong> of a 1-unit change in
<span class="math inline">\(x\)</span>:</p>
<pre class="r"><code>fixed.model = lm(y ~ 0 + p + x, data=data)  

summary(fixed.model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = y ~ 0 + p + x, data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6.13  -2.34  -0.17   1.74  10.31 
## 
## Coefficients:
##    Estimate Std. Error t value Pr(&gt;|t|)    
## p1    6.081      1.475    4.12  0.00016 ***
## p2    9.234      1.936    4.77  2.1e-05 ***
## p3   13.747      1.982    6.94  1.4e-08 ***
## p4   16.682      2.633    6.34  1.1e-07 ***
## p5   22.054      2.806    7.86  6.4e-10 ***
## x    -2.373      0.568   -4.18  0.00014 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.72 on 44 degrees of freedom
## Multiple R-squared:  0.813,  Adjusted R-squared:  0.787 
## F-statistic: 31.8 on 6 and 44 DF,  p-value: 1.86e-14</code></pre>
<p>So within levels of <span class="math inline">\(p\)</span>, a 1-unit
difference in <span class="math inline">\(x\)</span> is associated with
a -2.373 unit change in <span class="math inline">\(y\)</span>.</p>
<p>But what about the effect of the <strong>between-group</strong>
variance in <span class="math inline">\(x\)</span>?</p>
<p>The purest way to do this is to estimate a model with the group mean
values and the group mean centered predictor in a <strong>between-within
model</strong>:</p>
<pre class="r"><code>data |&gt; 
  group_by(p) |&gt; 
  mutate(x.m = mean(x),
         x.mc = x - x.m) |&gt; 
  ungroup() -&gt; data

bw.model &lt;- lmer(y ~ 1 + x.m + x.mc + (1|p), data = data)

summary(bw.model, correlation = F)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: y ~ 1 + x.m + x.mc + (1 | p)
##    Data: data
## 
## REML criterion at convergence: 272
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.8054 -0.6677 -0.0869  0.4676  2.8990 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  p        (Intercept)  3.62    1.90    
##  Residual             13.86    3.72    
## Number of obs: 50, groups:  p, 5
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   -2.240      3.134   -0.71
## x.m            2.651      0.945    2.81
## x.mc          -2.373      0.568   -4.18</code></pre>
<p>This gives the pure <strong>between-group effect</strong> of 2.651
<span class="math inline">\(y\)</span> change between levels of <span
class="math inline">\(p\)</span>, and the (orthogonal)
<strong>within-group effect</strong> of -2.373 <span
class="math inline">\(y\)</span> change with every 1-unit change in
<span class="math inline">\(x\)</span>, in a single between-within
model.</p>
<p><br></p>
<p>A logical next question is whether the between-group effect of <span
class="math inline">\(x\)</span> is different from the within-group
effect of <span class="math inline">\(x\)</span>. This is called the
<strong>contextual effect</strong> in psychology.</p>
<pre class="r"><code>context.model &lt;- lmer(y ~ 1 + x + x.m + (1|p), data = data)

summary(context.model, correlation = F)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: y ~ 1 + x + x.m + (1 | p)
##    Data: data
## 
## REML criterion at convergence: 272
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.8054 -0.6677 -0.0869  0.4676  2.8990 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  p        (Intercept)  3.62    1.90    
##  Residual             13.86    3.72    
## Number of obs: 50, groups:  p, 5
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   -2.240      3.134   -0.71
## x             -2.373      0.568   -4.18
## x.m            5.024      1.102    4.56</code></pre>
<p>The <strong>contextual effect</strong> is 5.024 units difference
between the orthogonal between- and within-effects (between —
within).</p>
<p><br></p>
<p>To determine whether this difference is non-zero, we can test it
against a model without the group mean predictor:</p>
<pre class="r"><code>anova(context.model, mixed.model)</code></pre>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<div class="kable-table">
<table>
<colgroup>
<col width="22%" />
<col width="7%" />
<col width="6%" />
<col width="6%" />
<col width="11%" />
<col width="14%" />
<col width="9%" />
<col width="4%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mixed.model</td>
<td align="right">4</td>
<td align="right">296</td>
<td align="right">303</td>
<td align="right">-144</td>
<td align="right">288</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">context.model</td>
<td align="right">5</td>
<td align="right">286</td>
<td align="right">296</td>
<td align="right">-138</td>
<td align="right">276</td>
<td align="right">11.5</td>
<td align="right">1</td>
<td align="right">0.001</td>
</tr>
</tbody>
</table>
</div>
<p>If the AIC and BIC of the contextual model are <em>smaller</em>, or
the Chisq is significant, then the contextual model is favoured.
Economists would argue the presence of contextual effects is a reason to
abandon a mixed model and go with a fixed effects model because it
implies endogenous effects are present, but that is really up to the
user. Personally, I like how the mixed modeling framework allows you to
investigate these types of differences.</p>
<p><br></p>
<p><br></p>
<p><br></p>
<p>* The weight of the uncentered coefficient is based on the ratio of
the standard error of the between- and within- estimate. As the standard
error of the between estimate increases relative to the within estimator
(i.e., it is less precise), the uncentered coefficient will be closer to
the within estimator (and vice-versa if within SE is larger).</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
